final Map<String, String> iconsForConditions = {
  'clear sky': 'assets/icons/sunny.svg',
  'few clouds': 'assets/icons/sunny_intervals.svg',
  'scattered clouds': 'assets/icons/white_cloud.svg',
  'mist': 'assets/icons/mist.svg',
  'haze': 'assets/icons/mist.svg',
  'Smoke': 'assets/icons/mist.svg',
  'sand/ dust whirls': 'assets/icons/mist.svg',
  'sand': 'assets/icons/mist.svg',
  'dust': 'assets/icons/mist.svg',
  'volcanic ash': 'assets/icons/mist.svg',
  'squalls': 'assets/icons/mist.svg',
  'tornado': 'assets/icons/mist.svg',
  'fog': 'assets/icons/fog.svg',
  'light rain': 'assets/icons/light_rain_showers.svg',
  'shower rain': 'assets/icons/light_rain_showers.svg',
  'ragged shower rain': 'assets/icons/light_rain_showers.svg',
  'moderate rain': 'assets/icons/light_rain_showers.svg',
  'heavy intensity rain': 'assets/icons/heavy_rain_showers.svg',
  'very heavy rain': 'assets/icons/heavy_rain_showers.svg',
  'extreme rain': 'assets/icons/heavy_rain_showers.svg',
  'light intensity shower rain': 'assets/icons/cloudy_with_light_rain.svg',
  'high intensity shower rain': 'assets/icons/cloudy_with_heavy_rain.svg',
  'freezing rain': 'assets/icons/sleet_showers.svg',
  'broken clouds': 'assets/icons/cloudy_with_sleet.svg',
  'overcast clouds': 'assets/icons/cloudy_with_sleet.svg',
  'light intensity drizzle': 'assets/icons/cloudy_with_light_rain.svg',
  'shower drizzle': 'assets/icons/cloudy_with_light_rain.svg',
  'shower rain and drizzle': 'assets/icons/cloudy_with_light_rain.svg',
  'drizzle': 'assets/icons/cloudy_with_light_rain.svg',
  'heavy intensity drizzle': 'assets/icons/cloudy_with_heavy_rain.svg',
  'light intensity drizzle rain': 'assets/icons/cloudy_with_light_rain.svg',
  'high intensity drizzle rain': 'assets/icons/cloudy_with_heavy_rain.svg',
  'drizzle rain': 'assets/icons/cloudy_with_light_rain.svg',
  'heavy shower rain and drizzle': 'assets/icons/cloudy_with_heavy_rain.svg',
  'thunderstorm with light rain': 'assets/icons/thundery_showers.svg',
  'thunderstorm rain': 'assets/icons/thundery_showers.svg',
  'thunderstorm with heavy rain': 'assets/icons/thunderstorms.svg',
  'light thunderstorm': 'assets/icons/thundery_showers.svg',
  'thunderstorm': 'assets/icons/thunderstorms.svg',
  'heavy thunderstorm': 'assets/icons/thunderstorms.svg',
  'ragged thunderstorm': 'assets/icons/thundery_showers.svg',
  'thunderstorm with light drizzle': 'assets/icons/thundery_showers.svg',
  'thunderstorm with drizzle': 'assets/icons/thundery_showers.svg',
  'thunderstorm with heavy drizzle': 'assets/icons/thunderstorms.svg',
};
